### ISSUE TITLE
config missing

### ISSUE THREAD

**Issue by Willem07** [TreyRuffy/BetterF3#26]
### Describe the Bug

A line in the config is missing

### Steps to Reproduce

Switch memory color toggle to off, restart minecraft, the value is reset

### Expected Behavior

The value will remain in the off position

### Screenshots

![2023-10-03_00 23 45](https://github.com/TreyRuffy/BetterF3/assets/51959206/18ddc9b9-e493-4031-aae5-371ad56b40f7)

### Modloader Type

Minecraft Forge

### Modloader Version

1.20.1-forge-47.2.0

### Mod Version

BetterF3-7.0.1-Forge-1.20.1

**Comment by TreyRuffy** [comment]
Fixed in 7.0.2 / 8.0.2
