### ISSUE TITLE
[Bug]: F3Debug interface is clipped

### ISSUE THREAD

**Issue by zrovihr** [TreyRuffy/BetterF3#28]
### Describe the Bug

I can only see the rest of the debugs if I make the window thinner, not on maximize mode. 
In this case, "Biome" debug is under the left side of the debug but it got clipped

It only clips when the GUI is at Large size (or auto).
Removing Rubidium does not fix it

### Steps to Reproduce

Press F3

### Expected Behavior

Not clipping

### Screenshots

![image](https://github.com/TreyRuffy/BetterF3/assets/38888951/33a2870f-90cc-4235-be1e-b84a833f6f4c)

### Modloader Type

Minecraft Forge

### Modloader Version

Forge 36.2.34

### Mod Version

BetterF3-1.5.0-Forge-1.16.5.jar

**Comment by TreyRuffy** [comment]
As a fix, open the F3 + M menu, and change the font scale. I'll look into changing it by default
