### ISSUE TITLE
[BUG] Servers show up as Incompatible in multiplayer if better F3 Forge is installed client side

### ISSUE THREAD

**Issue by starmun-0010** [TreyRuffy/BetterF3#3]
**Description**
This mod is client only but it is not configured as such, as a consequence the multiplayer servers show up as incompatible in the server list.

**To Reproduce**
1. Install Forge and the Better F3 mod on client. 
2. Create a forge 1.16.5 Minecraft server.
3. Add the server in multiplayer menu.
4. The server will show up as incompatible with a big red X.

**Expected behavior**
There should be a green checkmark besides the server marking it compatible.

**Screenshots**
![image](https://user-images.githubusercontent.com/5557278/114920305-bbc1c300-9e42-11eb-89ad-3421e8af59f6.png)
![image](https://user-images.githubusercontent.com/5557278/114920313-bcf2f000-9e42-11eb-85cc-360619e23063.png)

**Version Information**
 - OS Windows 10
 - Java Version: Java 8
 - Minecraft Version: . 1.16.5
 - Minecraft Forge Version: 36.1.4
 - Mod Version: BetterF3 Forge v1.1.2 (1.16.2-1.16.5)

**Additional context**
DISPLAYTEST extension point needs to be overridden to configure IGNORESERVERONLY.

**Comment by starmun-0010** [comment]
**Client log as requested**
[latest.log](https://github.com/TreyRuffy/BetterF3/files/6346647/latest.log)

**Server log (if needed)**
[latest.log](https://github.com/TreyRuffy/BetterF3/files/6346658/latest.log)

**Comment by starmun-0010** [comment]
Thank you for merging the pull request.
Any plans or releasing an update on curse forge with the fix?
Please let me know.

**Comment by TreyRuffy** [comment]
Yeah I'll do that tonight
