### ISSUE TITLE
[Bug]: GUI has left too much space

### ISSUE THREAD

**Issue by BenignPigeon** [TreyRuffy/BetterF3#58]
### Describe the Bug

When going into the GUI via modmenu or by F3+M there is too much space between the modules/too much padding of the modules.

### Steps to Reproduce

Go into the GUI via modmenu or by F3+M 

### Expected Behavior

It's easily viewable/editable and doesn't have that padding as shown in the screenshot.

### Screenshots

![image](https://github.com/TreyRuffy/BetterF3/assets/85837722/bcf620e1-6951-41c2-85e5-62c7756bdb61)
![image](https://github.com/TreyRuffy/BetterF3/assets/85837722/c02f0dbf-e8ad-4903-90cf-2ed715eb878e)
![image](https://github.com/TreyRuffy/BetterF3/assets/85837722/cd5c8e8d-3ad8-4778-99bd-47d67471e513)
![image](https://github.com/TreyRuffy/BetterF3/assets/85837722/991d68be-84ed-4806-90cc-b8b4af4412f3)

### Modloader Type

Fabric

### Modloader Version

0.15.3

### Mod Version

9.0.0

**Comment by Moonyol** [comment]
Not sure if this is related but pressing add new module then canceling or editing a module and canceling does this
![image](https://github.com/TreyRuffy/BetterF3/assets/92951072/c8ec2589-5aa0-4cad-8d67-73b35298eedb)

**Comment by humansouls** [comment]
any update on this?

**Comment by dolhpinweb** [comment]
i think it some sort of mods conflict, cuz i have same issue with emotecraft mod

**Comment by BigJohnson05** [comment]
> i think it some sort of mods conflict, cuz i have same issue with emotecraft mod

not a conflict issue, made a profile with betterf3, cloth config api and modmenu. issue still exists

**Comment by TreyRuffy** [comment]
Fixed in 9.0.1
