### ISSUE TITLE
[Bug]: Config menu is weird

### ISSUE THREAD

**Issue by amethyst-87** [TreyRuffy/BetterF3#68]
### Describe the Bug

Config menu has large padding between F3 items.
And after clicking one of them and coming back it gets worse. All screenshots down below,

### Steps to Reproduce

Enter config. (mod menu, in my case)

### Expected Behavior

Config menu looks right with normal padding.

### Screenshots

![image](https://github.com/TreyRuffy/BetterF3/assets/150542561/aca06082-ddcc-4e93-8fa8-0f97bd29d009)
![image](https://github.com/TreyRuffy/BetterF3/assets/150542561/35029751-56c0-41aa-b022-273ced2048b6)

### Modloader Type

Fabric

### Modloader Version

0.15.7

### Mod Version

9.0

### Additional Context

Mods folder:
![image](https://github.com/TreyRuffy/BetterF3/assets/150542561/960305e4-f292-424a-9167-39b39c6ee7dc)

**Comment by TreyRuffy** [comment]
Fixed in 9.0.1
