### ISSUE TITLE
[Bug]: Crash when disabling right module 'Misc Right'

### ISSUE THREAD

**Issue by AstudilloMarillo** [TreyRuffy/BetterF3#91]
### Describe the Bug

The game crashes when trying to disable the right module 'Misc Right' or when trying to open the F3 menu with 'Misc Right' disabled.

### Steps to Reproduce

Disable the right module 'Misc Right'.

### Expected Behavior

No crash, correctly disable the module.

### Modloader Type

Fabric

### Modloader Version

0.15.11

### Mod Version

11.0.0

**Comment by lewistrm** [comment]
read my issue below yours, the issue isnt when you disable misc, its when you have 0 text on the right side of the screen at all

**Comment by TreyRuffy** [comment]
Fixed in 11.0.1
